language: go

go:
    - "1.10.x"
    - "1.11.x"
    - "1.12.x"
    
notifications:
    email:
        recipients:
            - chadtakahashi@gmail.com
        on_success: always
        on_failure: always
