language: go

go:
    - "1.11.x"
    - "1.12.x"

script:
    - env GO111MODULE=on make

notifications:
    email:
        recipients:
            - chadtakahashi@gmail.com
        on_success: always
        on_failure: always
